"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.bioList = exports.animalList = void 0;
var animalList;
(function (animalList) {
    animalList[animalList["Bat"] = 0] = "Bat";
    animalList[animalList["bear"] = 1] = "bear";
    animalList[animalList["bee"] = 2] = "bee";
    animalList[animalList["bird"] = 3] = "bird";
    animalList[animalList["butterfly"] = 4] = "butterfly";
    animalList[animalList["camel"] = 5] = "camel";
    animalList[animalList["cat"] = 6] = "cat";
    animalList[animalList["chameleon"] = 7] = "chameleon";
    animalList[animalList["chicken"] = 8] = "chicken";
    animalList[animalList["clownfish"] = 9] = "clownfish";
    animalList[animalList["cow"] = 10] = "cow";
    animalList[animalList["crab"] = 11] = "crab";
    animalList[animalList["crocodile"] = 12] = "crocodile";
    animalList[animalList["dog"] = 13] = "dog";
    animalList[animalList["dolphin"] = 14] = "dolphin";
    animalList[animalList["duck"] = 15] = "duck";
    animalList[animalList[" elephant"] = 16] = " elephant";
    animalList[animalList["flamingo"] = 17] = "flamingo";
    animalList[animalList["fox"] = 18] = "fox";
    animalList[animalList["frog"] = 19] = "frog";
    animalList[animalList["giraffe"] = 20] = "giraffe";
    animalList[animalList["hedgehog"] = 21] = "hedgehog";
    animalList[animalList["hippopotamus"] = 22] = "hippopotamus";
    animalList[animalList["horse"] = 23] = "horse";
    animalList[animalList["kangaroo"] = 24] = "kangaroo";
    animalList[animalList["koala"] = 25] = "koala";
    animalList[animalList["lion"] = 26] = "lion";
    animalList[animalList["llama"] = 27] = "llama";
    animalList[animalList["manta-ray"] = 28] = "manta-ray";
    animalList[animalList["monkey"] = 29] = "monkey";
})(animalList || (animalList = {}));
exports.animalList = animalList;
var bioList;
(function (bioList) {
    bioList[bioList["mammals"] = 0] = "mammals";
    bioList[bioList["fish and aquatic"] = 1] = "fish and aquatic";
    bioList[bioList["reptiles"] = 2] = "reptiles";
    bioList[bioList["insects"] = 3] = "insects";
    bioList[bioList["amphibians"] = 4] = "amphibians";
    bioList[bioList["birds"] = 5] = "birds";
    bioList[bioList["others"] = 6] = "others";
})(bioList || (bioList = {}));
exports.bioList = bioList;
